version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy $MASTER-flask-StarWars

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
